root: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 5

env:
  es6: true
  node: true

rules:
  brace-style:
    - error
    - allman
  comma-dangle:
    - error
    - always-multiline
  curly:
    - error
  eqeqeq:
    - error
  indent:
    - error
    - tab
    -
      SwitchCase: 1
      VariableDeclarator: 0
  linebreak-style:
    - error
    - unix
  no-constant-condition:
    - off
  one-var:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
